using System;
using PRAManager;
using Mindjet.MindManager.Interop;
using System.Drawing;
using System.Windows.Forms;
using System.Collections.Generic;

namespace Bubbles
{
    internal class OmniTools
    {
        public static void RunTool(string path, Form form = null, string orientation = "")
        {
            switch (path)
            {
                case "OT_SaveAll":
                    foreach (Document doc in MMUtils.MindManager.AllDocuments)
                        doc.Save();
                    break;
                case "OT_CloseAll":
                    if (MMUtils.ActiveDocument == null) return;

                    Document active = MMUtils.ActiveDocument;

                    foreach (Document doc in MMUtils.MindManager.AllDocuments)
                    {
                        if (doc.IsModified)
                        {
                            if (savemapsaskme)
                            {
                                DialogResult dr = MessageBox.Show(
                                    String.Format(Utils.getString("tools.closenotsaved"), doc.CentralTopic.Text), "MindManager",
                                    MessageBoxButtons.YesNoCancel, MessageBoxIcon.Question);

                                if (dr != DialogResult.Yes) continue;
                            }
                            doc.Save();
                        }
                    }

                    foreach (Document doc in MMUtils.MindManager.AllDocuments)
                    {
                        if (doc == active && donotcloseactivemap) continue;
                        doc.Close();
                    }
                    break;
                case "OT_MapContent":
                    if (MMUtils.ActiveDocument == null) return;

                    if (aNavigationDlg == null || aNavigationDlg.IsDisposed || !aNavigationDlg.Visible)
                    {
                        aNavigationDlg = null;
                        aNavigationDlg = new MapContentDlg();
                    }
                    else return;

                    int topicCount = MMUtils.ActiveDocument.CentralTopic.SubTopics.Count + 1;
                    int itemheight = aNavigationDlg.listView1.GetItemRect(0).Height;

                    if (topicCount <= 10) // If not a big amount, change height to adjust items count 
                    {
                        aNavigationDlg.thisHeight = topicCount * itemheight + aNavigationDlg.itemHeight.Width;
                        aNavigationDlg.listView1.Scrollable = false;
                    }

                    // Get tools list location
                    Rectangle child = aNavigationDlg.RectangleToScreen(aNavigationDlg.ClientRectangle);
                    aNavigationDlg.Location = StixUtils.GetChildLocation(form, child, orientation, "tools");

                    aNavigationDlg.Show(new WindowWrapper((IntPtr)MMUtils.MindManager.hWnd));
                    break;
            }
        }

        public static void GetAppIcons()
        {
            WindowsAppIcons["WT_{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\\charmap.exe"] = "tool-Charmap.png";
            WindowsAppIcons["WT_Microsoft.Paint_8wekyb3d8bbwe!App"] = "tool-Paint.png";
            WindowsAppIcons["WT_Microsoft.OutlookForWindows_8wekyb3d8bbwe!Microsoft.OutlookforWindows"] = "tool-Outlook.png";
            WindowsAppIcons["WT_Microsoft.PowerAutomateDesktop_8wekyb3d8bbwe!PAD.Console"] = "tool-PowerAutomate.png";
            WindowsAppIcons["WT_{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\\printmanagement.msc"] = "tool-printmanagement.png";
            WindowsAppIcons["WT_windows.immersivecontrolpanel_cw5n1h2txyewy!microsoft.windows.immersivecontrolpanel"] = "tool-settings.png";
            WindowsAppIcons["WT_{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\\msinfo32.exe"] = "tool-SystemInformation.png";
            WindowsAppIcons["WT_5319275A.WhatsAppDesktop_cv1g1gvanyjgm!App"] = "tool-WhatsApp.png";
            WindowsAppIcons["WT_Microsoft.AutoGenerated.{DAA168DE-4306-C8BC-8C11-B596240BDDED}"] = "tool-SpeechRecognition.png";
            WindowsAppIcons["WT_Chrome._crx_agimnkijcamfeangaknmldooml"] = "tool-youtube.png";
            WindowsAppIcons["WT_Microsoft.WindowsNotepad_8wekyb3d8bbwe!App"] = "tool-winnotepad.png";
            WindowsAppIcons["WT_Microsoft.MicrosoftStickyNotes_8wekyb3d8bbwe!App"] = "tool-StickyNotes.png";
            WindowsAppIcons["WT_Microsoft.WindowsSoundRecorder_8wekyb3d8bbwe!App"] = "tool-SoundRecorder.png";
            WindowsAppIcons["WT_microsoft.windowscommunicationsapps_8wekyb3d8bbwe!microsoft.windowslive.calendar"] = "tool-wcalendar.png";
            WindowsAppIcons["WT_Microsoft.WindowsCalculator_8wekyb3d8bbwe!App"] = "tool-wcalculator.png";
            WindowsAppIcons["WT_Microsoft.WindowsCamera_8wekyb3d8bbwe!App"] = "tool-camera.png";
            WindowsAppIcons["WT_Microsoft.WindowsMaps_8wekyb3d8bbwe!App"] = "tool-wmaps.png";
            WindowsAppIcons["WT_Microsoft.ZuneVideo_8wekyb3d8bbwe!Microsoft.ZuneVideo"] = "tool-ZuneVideo.png";
            WindowsAppIcons["WT_Microsoft.ZuneMusic_8wekyb3d8bbwe!Microsoft.ZuneMusic"] = "tool-ZuneMusic.png";
            WindowsAppIcons["WT_Microsoft.BingNews_8wekyb3d8bbwe!AppexNews"] = "tool-BingNews.png";
            WindowsAppIcons["WT_Microsoft.ScreenSketch_8wekyb3d8bbwe!App"] = "tool-ScreenSketch.png";
            WindowsAppIcons["WT_Microsoft.BingWeather_8wekyb3d8bbwe!App"] = "tool-BingWeather.png";
            WindowsAppIcons["WT_microsoft.windowscommunicationsapps_8wekyb3d8bbwe!microsoft.windowslive.mail"] = "tool-wmail.png";
            WindowsAppIcons["WT_Microsoft.Windows.Photos_8wekyb3d8bbwe!App"] = "tool-mphotos.png";
            WindowsAppIcons["WT_Microsoft.WindowsAlarms_8wekyb3d8bbwe!App"] = "tool-clock.png";
            WindowsAppIcons["WT_Microsoft.YourPhone_8wekyb3d8bbwe!App"] = "tool-pcphone.png";
            WindowsAppIcons["WT_Clipchamp.Clipchamp_yxz26nhyzhsrt!App"] = "tool-Clipchamp.png";
            WindowsAppIcons["WT_Microsoft.WindowsStore_8wekyb3d8bbwe!App"] = "tool-WindowsStore.png";
            WindowsAppIcons["WT_MicrosoftTeams_8wekyb3d8bbwe!MicrosoftTeams"] = "tool-MicrosoftTeams.png";
            WindowsAppIcons["WT_Microsoft.Todos_8wekyb3d8bbwe!App"] = "tool-Todos.png";
            WindowsAppIcons["WT_Microsoft.Office.OUTLOOK.EXE.15"] = "tool-OUTLOOK.png";
            WindowsAppIcons["WT_Microsoft.Windows.Shell.RunDialog"] = "tool-wrun.png";
            WindowsAppIcons["WT_Microsoft.Windows.AdministrativeTools"] = "tool-windowstools.png";
            WindowsAppIcons["WT_Microsoft.Office.WINWORD.EXE.15"] = "tool-WINWORD.png";
            WindowsAppIcons["WT_Microsoft.GamingApp_8wekyb3d8bbwe!Microsoft.Xbox.App"] = "tool-xbox.png";
            WindowsAppIcons["Microsoft.AutoGenerated.{C1C6F8AC-40A3-0F5C-146F-65A9DC70BBB4}"] = "tool-scheduler.png";
            WindowsAppIcons["WT_Microsoft.Windows.ControlPanel"] = "tool-ControlPanel.png";
            WindowsAppIcons["WT_Microsoft.Office.EXCEL.EXE.15"] = "tool-EXCEL.png";
            WindowsAppIcons["WT_Microsoft.Windows.Explorer"] = "tool-WExplorer.png";
            WindowsAppIcons["WT_Microsoft.MicrosoftOfficeHub_8wekyb3d8bbwe!Microsoft.MicrosoftOfficeHub"] = "tool-ms365.png";
            WindowsAppIcons["WT_Microsoft.Office.WINWORD.EXE.15"] = "tool-WINWORD.png";
        }

        public static Dictionary<string, string> WindowsAppIcons = new Dictionary<string, string>();

        static MapContentDlg aNavigationDlg = null;

        public static bool savemapsaskme = false;
        public static bool donotcloseactivemap = true;
    }
}
